name: Test and Deployment Workflow

on:
  pull_request_review:
    types: [submitted]
    branches:
      - main

jobs:
  test-and-merge:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Echo a message
        run: echo "Test and Deployment Workflow triggered by approval."
      - name: Merge PR
        if: contains(fromJson('["sakariye223"]'), github.actor)
        run: echo "PR would be merged now by ${github.actor}"
        # Replace the echo command with actual merge commands if needed later
